name: tokenizer
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - spacy>=2.2
  - gensim
  - tqdm
  - jieba
  - pymorphy2
  - pylint
  - pip
  - pip:
    - pymorphy2-dicts
    - pythainlp
    - pyvi
    - mecab-python3
